server:
    port: 8080
    session:
        timeout: 1800 # 秒

spring:
    application:
        name: HBKF

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    logging:
        level: debug
        path: ${user.home}/Desktop/logs.txt

    mvc:
        view:
            prefix: /
            suffix: .jsp

    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.70.204:3306/tams?characterEncoding=utf8&useSSL=true
        username: tams
        password: tams
